### ISSUE TITLE
[cling] Function definition is not allowed here

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-cling#40]
Where declaring a variable before defining a function in cell, we get:

![split](https://user-images.githubusercontent.com/2397974/29083651-ba4129c0-7c69-11e7-9627-5e8ac5c40a6d.png)

However, declaring the variable after the function or separating the two statement in two cells works fine.

**Comment by gouarin** [comment]
If you invert the order it works. So, I am not sure that it is a xeus-cling issue...

![split](https://user-images.githubusercontent.com/7510549/29238697-b6a8c13c-7f3a-11e7-8217-245ec25cebcd.png)

**Comment by nthiery** [comment]
A variant: a single cell containing two functions:
```
int f(int i) {
    return 2;
}
int g(int i) {
    return 3;
}
```
triggers an error:
```
input_line_7:5:15: error: function definition is not allowed here
 int g(int i) {
              ^
```

**Comment by nthiery** [comment]
Other variant:
```
using namespace std;
int f(int i) {
    return 1;
}
```

**Comment by SylvainCorlay** [comment]
This has been solved upstream and will be resolved when we update to the latest version of cling.

**Comment by nthiery** [comment]
>    This has been solved upstream and will be resolved when we update to
>    the latest version of cling.

Great!

**Comment by nthiery** [comment]
For the record, another instance:
```
vector<int> f() {
     return {};
}
```
triggers also a function definition not allowed here. Alas we can't update easily, and this is annoying for the coming week which is about functions and vectors. Would you by any chance have a workaround?
One thing that work is to use a 
```
typedef vector<int> tableau
```
but this adds another thing to explain to our students.

Thanks in advance,

**Comment by gouarin** [comment]
@nthiery this issue has been fixed in the master branch of cling https://github.com/root-project/cling/issues/182

We hope that we can have a newest version of cling for xeus-cling soon.

A better workaround is to use auto

```
auto f()
{
    return std::vector<int>{};
}
```

So you have to follow the rule of AAA (Almost Always Auto) ;)

**Comment by nthiery** [comment]
On Sun, Oct 08, 2017 at 02:35:28PM -0700, Loic Gouarin wrote:
>    [1]@nthiery this issue has been fixed in the master branch of cling
>    [2]root-project/cling#182
> 
>    We hope that we can have a newest version of cling for xeus-cling soon.

Yup.

>    A better workaround is to use auto
> auto f()
> {
>     return std::vector<int>{};
> }
> 
>    So you have to follow the rule of AAA (Almost Always Auto) ;)

Ah right, of course.

That's indeed the solution I would want to teach them in the longer
run. However they only have 3 weeks of programming in their fingers,
so I had implicitly crossed out the use of auto in my mind. Now I need
to think whether I want to keep crossing it out or not. That's one
more concept to introduce and we chose to use C++ rather than Python
to be more explicit on static types.

Hmm, pondering, pondering, ...

Thanks Loïc!

**Comment by nthiery** [comment]
Shoot, `auto` as return type is C++14, and we are for now just using C++ 11. Ok, maybe we should switch, but not tomorrow. I'll use a typedef for now ...

**Comment by momonala** [comment]
Does anyone know why this causes an issue: 

```c++
std::tuple<std::string, int> testTuple()
{
    std::string s = "string"; 
    int i = 0; 
    return std::make_pair(s, i); 
}

```

**Comment by gouarin** [comment]
@momonala this is due to the presence of `<`, `>` characters in the return type. If you use `auto`, your problem is gone ;).

It is fixed in the cling 0.5 version.

**Comment by suniljaya** [comment]
.rawInput
funtion()

**Comment by nthiery** [comment]
This is still failing with cling 0.5:
```
vector<int> f() {
    return vector<int>
}
```
```
input_line_9:2:18: error: function definition is not allowed here
 vector<int> f() {
                 ^
```
```
 (info-111) [~] conda list | grep cling                                                                                                                                                                   clangdev                  5.0.0                   cling_1  [cling]  QuantStack
cling                     0.5                           7  [cling]  QuantStack
cling-patches             1                             0    conda-forge
cryptopp                  5.6.5                   cling_0  [cling]  QuantStack
llvmdev                   5.0.0                   cling_1  [cling]  QuantStack
pyzmq                     17.0.0                  cling_0  [cling]  QuantStack
xeus                      0.14.1                  cling_0  [cling]  QuantStack
xeus-cling                0.4.7                         0    QuantStack
zeromq                    4.2.5                   cling_0  [cling]  QuantStack
```

**Comment by srpgilles** [comment]
Yet another case: instantiation of a friend function:

```
class Vector3
{
    public :

        Vector3(double x, double y, double z);
        Vector3() = default;

        friend Vector3 operator+(const Vector3& v1, const Vector3& v2);

    private :
    
        double x_ = 0.;
        double y_ = 0.;
        double z_ = 0.;
}; 

// In another cell:
Vector3 operator+(const Vector3& v1, const Vector3& v2)
{    
    Vector3 ret;
    ret.x_ = v1.x_ + v2.x_;
    ret.y_ = v1.y_ + v2.y_;
    ret.z_ = v1.z_ + v2.z_;
    
    return ret;
}
```

**Comment by nthiery** [comment]
Hi!

The examples are still failing. Any hope for progress? Why has this ticket been closed?

**Comment by kkufieta** [comment]
I second this thread, it's still an issue.

This fails (Interpreter Error: )
```cpp
vector<vector<int>> SimpleTest() {
    vector<vector<int>> v {{1, 2, 3}, {4, 5, 6}};
    return v;
}
```
```bash
input_line_44:2:35: error: function definition is not allowed here
 vector<vector<int>> SimpleTest() {
```

This runs just fine:
```cpp
auto SimpleTest() {
    vector<vector<int>> v {{1, 2, 3}, {4, 5, 6}};
    return v;
}
```

**Comment by nthiery** [comment]
Any reason for not reopening this ticket?

**Comment by JohanMabille** [comment]
Do you have the error with cling? If so , this is a bug to report upstream, otherwise we can reopen this issue.

**Comment by nthiery** [comment]
Salut Johan!

I just tried, and did not manage: 
```
cling
****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ auto i=3;
[cling]$ void foo() {}
```

But I am not sure whether this is relevant: it's indeed not clear to me
how to reproduce this in plain cling: here how to group the two lines
so that they are evaluated at once, like when they are in the same cell.

**Comment by nthiery** [comment]
This one does fail though:
```
[cling]$ #include <vector>
[cling]$ using namespace std;
[cling]$ vector<int> f() {
[cling]$ ?       return vector<int>
[cling]$ ?   }
input_line_7:2:18: error: function definition is not allowed here
 vector<int> f() {
                 ^
```

**Comment by JohanMabille** [comment]
@nthiery you can define a multiline function in cling, just hit enter after you open the curly brace. You will see a question mark on the new line (and on each new line until you close the curly brace).

**Comment by nthiery** [comment]
> @nthiery you can define a multiline function in cling, just hit enter after you open the curly brace. You will see a question mark on the new line (and on each new line until you close the curly brace).

Indeed; I just made it a one-liner for conciseness.

What I don't know how to do (and if it even makes sense) is to put two
functions at once. As if they were in the same cell.

Oh, but now that you make me think about it; this ought to be valid
code, but it's not:

```
[cling]$ void f() {} void g() {}
input_line_4:2:11: error: function definition is not allowed here
```

So in summary: several thing in a single cell is behaving like several
thing in a single input line for cling. And the latter has limitations.

**Comment by jm-boley** [comment]
Not to beat a dead horse, but yet another example:

using coord_ext = std::array<float, 6>;
using surf_normal = std::array<float, 3>;
using face_data = std::tuple<coord_ext, coord_ext, coord_ext, coord_ext, surf_normal>;

auto generate_quad_strip(std::vector<coord_ext> rib1, std::vector<coord_ext> rib2)
{
    vector<face_data> quad_strip;
    auto rib1_iter = std::begin(rib1),
         rib2_iter = std::begin(rib2),
          rib1_end = std::end(rib1),
          rib2_end = std::end(rib2);

    /*
        ...[snip]...
     */

    return quad_strip;
}

**Comment by parik-lum** [comment]
Are we reopening this ticket since this issue still seems to persist in latest cling versions.

**Comment by lucasturci** [comment]
Hi!

Is it failing for any function now or am I doing something wrong?
```cpp
#include <iostream>

using namespace std;

void f() {
    cout << "Hi" << endl;
}
```

The kernel complains about `f()`. And every modification I tried failed...

**Comment by nthiery** [comment]
Hi @lucasturci. Have you tried putting the function definition just by itself in a separate cell?
IIRC that is still needed,

**Comment by lucasturci** [comment]
> Hi @lucasturci. Have you tried putting the function definition just by itself in a separate cell?
> IIRC that is still needed,

Yeah, it worked, thanks!

**Comment by dslowik44** [comment]
So... What does xeus-cling remember across cells and what does it forget?

**Comment by Lancelof2019** [comment]
#include<iostream>
using namespace std;
int main()
    
{
    
    cout<<"Hello jupyter"<<endl;
    
}
input_line_16:5:1: error: function definition is not allowed here
{
^

**Comment by Lancelof2019** [comment]
I used include<iostream> but this ca not be displayed in forum.

**Comment by Lancelof2019** [comment]
If I import new C++ files,I can not find 'run' button in jupyter.

**Comment by Lancelof2019** [comment]
(cling) [root@localhost MA]# jupyter kernelspec list
Available kernels:
  python3    /root/.conda/envs/mws/share/jupyter/kernels/python3
  xcpp14     /usr/local/share/jupyter/kernels/xcpp14

**Comment by martinRenou** [comment]
Please try to split your cell in two:

```cpp
#include <iostream>
using namespace std;
```

Then:
```
int main()
    
{   
    cout<<"Hello jupyter"<<endl;  
}
```

Also note that you don't need a `main` function, the notebook content is already the main.

**Comment by Lancelof2019** [comment]
> Please try to split your cell in two:
> 
> ```c++
> #include <iostream>
> using namespace std;
> ```
> 
> Then in another cell:
> 
> ```c++
> int main()
>     
> {   
>     cout<<"Hello jupyter"<<endl;  
> }
> ```
> 
> Also note that you don't need a `main` function, the notebook content is already the main.

Thanks,Martin,it works.

**Comment by YuhePan** [comment]
This is still failing with cling 0.9:
![image](https://github.com/jupyter-xeus/xeus-cling/assets/84851861/d8528fe0-779b-4ffe-ad7e-e47e1d8bff0d)

![image](https://github.com/jupyter-xeus/xeus-cling/assets/84851861/e78b46ec-dc6b-417f-8f90-e83846480daa)

and when I split my cell in two, it doesn't work

**Comment by martinRenou** [comment]
How do you split them?

You need to put function definitions alone in cells, so that would probably be three cells in your case (includes, `add` implementation and `main` implementation).

> Also note that you don't need a main function, the notebook content is already the main.

**Comment by YuhePan** [comment]
> 

Cool! I got it, thank you very much. And I'm very sorry for misunderstanding earlier. : )

**Comment by YuhePan** [comment]
> How do you split them?
> 
> You need to put function definitions alone in cells, so that would probably be three cells in your case (includes, `add` implementation and `main` implementation).
> 
> > Also note that you don't need a main function, the notebook content is already the main.

Cool! I got it, thank you very much. And I'm very sorry for misunderstanding earlier. : )

**Comment by martinRenou** [comment]
No worries, happy that you got it working

**Comment by xiebinghua** [comment]
I also meet this problem and I maybe solve it.

**Comment by xiebinghua** [comment]
I also meet this problem and I maybe know how to solve it.
you should define a function in a single cell.
![image](https://github.com/jupyter-xeus/xeus-cling/assets/40881816/1ba46850-f33a-4633-8ade-7e54b17fefd3)

**Comment by xiebinghua** [comment]
![image](https://github.com/jupyter-xeus/xeus-cling/assets/40881816/2c2e45ee-5876-4bd0-a9a0-161bc74b97ca)
this is my xeus-cling edition

**Comment by mo-han** [comment]
@xiebinghua 
so it's feature, not bug

**Comment by srpgilles** [comment]
Doesn't seem to me like it's a cling limitation.

If I'm testing the following code with [cppyy](https://cppyy.readthedocs.io/en/latest/) (a Python module which wraps cling and is to my mind the easiest way to use cling) it works flawlessly (you may see each function call as a cell):

```python
import cppyy

cppyy.cppdef("""
        float fn1(float r)
        {
             int temp = r+1;
             return temp;             
        }
             
         float fn2(float r)
        {
             int temp = r+1;
             return temp;             
        }
""")
```

```python
cppyy.cppexec("""
    #include <iostream>
              
    std::cout << fn1(5.) << std::endl;
    std::cout << fn2(5.) << std::endl;
""")
```
